image:
  file: gitpod/debian.Dockerfile

# FIXME: Change gitpod user on GITPOD_GIT_USER_NAME env value

tasks:
  # Does not accept Quotation without '|' ?
  - init: |
      printf 'FIXME: %s\n' "Get rid of me"
    command: |
      printf 'FIXME: %s\n' "This is a hotfix for https://github.com/gitpod-io/gitpod/issues/1252 manipulating PS1 env var"
      export PS1="\033[1m\e[38;5;201m[ \t : \w : EXIT \$? ]\033[0m\e[38;5;011m\n\u@gitpod \\$ \[$(tput sgr0)\]"
      #           ^^^^^^^ - bolt
      #                  ^^^^^^^^^^^^ - Purple color
      #                                                    ^^^^^^ - remove bolt
      #                                                           ^^^^^^^^^^^ - Gold color
